- .vscode/settings.json
- package-lock.json
- package.json
- src/Actions/AppActions/appActions.js
- src/App.js
- src/Components/Home/Home.jsx
- src/Components/Layout/Layout.jsx
- src/Reducer/index.js
- src/index.js
- src/store.js
Instalación de dependencias, React, redux, react-router-dom, react-redux, redux-thunk;  
Configuración del Store;
Creación de Reducer app compuesto;
Creacion de carpeta Actions con App Action Loading;
Creación de componentes Home y layout sin codigo;
Se agregan componentes al App con path y route predeterminado;
> Pasos Iniciales Frontend

- src/App.js
> Actualizar App.js

- src/App.js
- src/Components/FormCreacion/CrearEvento.jsx
- src/Components/Nav/Nav.css
- src/Components/Nav/Nav.jsx
El Nav queda asi 
En App puse que "/" sea el "/home"
> acomodando Nav y App.js

- src/Actions/AppActions/appActions.js
- src/App.js
- src/Components/Eventos/EventoList.css
- src/Components/Eventos/EventosList.jsx
- src/Components/Filtros/Filtros.css
- src/Components/Filtros/Filtros.jsx
- src/Components/Nav/Nav.jsx
- src/Components/Paginado/Paginado.jsx
- src/Reducer/index.js
- src/store.js
Realicé los componentes Paginado, Eventos y Filtros, lo cual solo tiene funcionalidad Filtros por categoría, ya que ordenamientos lo deje comentado porque estoy resolviendo el porque no andan si esta todo bien jaja
Esto lleva tmb a cambios en redux con estados y acciones.
En el Nav se vinculó "Eventos" con la pagina "/eventos"
Por ahora quedó asi.
> Filtros por categoria

- src/Actions/AppActions/appActions.js
- src/App.js
- src/Components/Error404/Error404.jsx
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Eventos/EventosList.jsx
- src/Components/Exhibits/Exhibits.jsx
- src/Components/Login/Login.jsx
- src/Components/Nav/Nav.jsx
- src/Reducer/index.js
> detalles de los eventos

- src/Components/EventDetails/EventDetail.css
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Eventos/EventosList.jsx
- src/Components/Filtros/Filtros.jsx
- src/Components/Paginado/Paginado.jsx
Estilos para los detalles de los eventos
> styles detalles-evento

- src/Components/Dashboard/Dashboard.css
- src/Components/Dashboard/Dashboard.jsx
> responsive dash

- src/Components/Eventos/EventoList.css
- src/Components/Eventos/EventosList.jsx
- src/Components/Filtros/Filtros.css
- src/Components/Filtros/Filtros.jsx
Arreglo detalles responsive de la lista de eventos y filtros
> responsive card/filtros

- src/Components/Comentarios/CommentForm.css
- src/Components/Comentarios/CommentForm.jsx
- src/Components/Comentarios/Stars.jsx
- src/Components/Dashboard/Dashboard.css
- src/Components/Dashboard/Dashboard.jsx
- src/Components/EventDetails/EventDetail.css
- src/Components/EventDetails/EventDetails.jsx
- src/Components/FormCreacion/CrearEvento.jsx
Componentes realizados anteriormente por Gabi
> starts y comentarios en evento

- src/Components/Dashboard/Dashboard.jsx
- src/Components/Dashboard/Eventos/Agregar.jsx
- src/Components/Dashboard/Eventos/Modificar.jsx
- src/Components/Dashboard/Menu-desplegable.jsx
- src/Components/Dashboard/Usuarios/Agregar.jsx
- src/Components/Dashboard/Usuarios/Modificar.jsx
- src/Components/FormCreacion/CrearUsuario.jsx
- src/Components/FormCreacion/ModificarEvento.jsx
- src/Components/FormCreacion/ModificarUsuario.jsx
- src/Components/Nav/Nav.jsx
Componentes para agregar y editar Eventos y Usuarios.
Usuarios todavia sin logica, solo visual. Eventos solo crear completo.
Sin rutas en App ya que están codeando los del back.
> Componentes dashboard

- src/App.js
> rutas dashboard

- src/App.js
- src/Components/Dashboard/Categorias/Agregar.jsx
- src/Components/Dashboard/Categorias/Modificar.jsx
- src/Components/Dashboard/Comentarios/Modificar.jsx
- src/Components/Dashboard/Eventos/Agregar.jsx
- src/Components/Dashboard/Eventos/Modificar.jsx
- src/Components/Dashboard/Guias/Agregar.jsx
- src/Components/Dashboard/Guias/Modificar.jsx
- src/Components/Dashboard/Menu-desplegable.jsx
- src/Components/Dashboard/Usuarios/Agregar.jsx
- src/Components/FormCreacion/CrearCategoria.jsx
- src/Components/FormCreacion/CrearEvento.jsx
- src/Components/FormCreacion/CrearGuia.jsx
- src/Components/FormCreacion/ModificarCategoria.jsx
- src/Components/FormCreacion/ModificarComentario.jsx
- src/Components/FormCreacion/ModificarGuia.jsx
- src/Components/FormCreacion/ModificarUsuario.jsx
- src/Components/Login/Login.css
- src/Components/Login/Login.jsx
- src/Components/Login/Logout.jsx
- src/Components/Nav/Nav.css
Estos componentes no tienen logica con el back aún.
Crear Usuario
Modificar Usuario
Crear Evento
Modificar Evento
Modificar Comentario
Crear Guia
Modificar Guia
Crear Categoria
Modificar Categoria
> forms del dash

- src/Components/Comentarios/CommentForm.jsx
- src/Components/Eventos/EventosList.jsx
- src/Components/Filtros/Filtros.css
- src/Components/Filtros/Filtros.jsx
- src/Components/Login/Login.css
- src/Components/Login/Profile.jsx
- src/Components/Paginado/Paginado.css
- src/Components/Paginado/Paginado.jsx
> peginado y login estetico

- src/App.js
- src/Components/Dashboard/Categorias/Agregar.jsx
- src/Components/Dashboard/Categorias/Modificar.jsx
- src/Components/Dashboard/Comentarios/Modificar.jsx
- src/Components/Dashboard/Dashboard/Dashboard-Inicio.jsx
- src/Components/Dashboard/Eventos/Agregar.jsx
- src/Components/Dashboard/Eventos/Modificar.jsx
- src/Components/Dashboard/Guias/Agregar.jsx
- src/Components/Dashboard/Guias/Modificar.jsx
- src/Components/Dashboard/Menu-desplegable.jsx
- src/Components/Dashboard/Usuarios/Agregar.jsx
- src/Components/Dashboard/Usuarios/Modificar.jsx
- src/Components/Login/Login.css
- src/Components/Login/Profile.jsx
- src/Components/Nav/Nav.jsx
> dashboard, nav y cerrar sesion

- package-lock.json
- package.json
- public/index.html
- src/Actions/AppActions/appActions.js
- src/Components/Payment/Payment.jsx
- src/Components/Paypal/PayPal.js
- src/Reducer/index.js
> Brayan men

- src/App.js
- src/Components/CartSidebar/CartSidebar.jsx
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Nav/Nav.jsx
- src/Context/index.js
- src/Context/useLocalStorage.js
Aplique el custom hook para permanencia de estado del carrito siendo llamado desde cualquier parte del app sin ser pasado como props sino como useContext
> creacion y aplicacion de hook localstorage evitando parsear

- src/Components/Eventos/EventosList.jsx
- src/Components/Filtros/Filtros.css
- src/Components/Filtros/Filtros.jsx
- src/Components/SearchBar/SearchBar.css
- src/Components/SearchBar/SearchBar.jsx
Searchbar solo escribiendo busca, filtrados y ordenamientos responsivos
> detalles filtros y searchbar

- package-lock.json
- package.json
- src/Components/EventDetails/SmallEvent.jsx
- src/Components/FormCreacion/CrearEvento.css
- src/Components/FormCreacion/ModificarEvento.jsx
- src/Components/SearchBar/SearchBar.css
- src/index.css
Se modifican los eventos, buscando cual modificar.
> put evento

- src/Actions/AppActions/appActions.js
- src/Components/FormCreacion/CrearUsuario.jsx
- src/Components/FormCreacion/ModificarGuia.jsx
- src/Reducer/index.js
> modificacion guia

- src/Actions/AppActions/appActions.js
- src/Components/Comentarios/CommentForm.jsx
- src/Components/Comentarios/FormReview.css
- src/Components/Comentarios/FormReview.jsx
- src/Components/Comentarios/FormReviewInvitado.jsx
- src/Components/EventDetails/EventDetail.css
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Eventos/EventosList.jsx
- src/Reducer/index.js
Cuando no se está logueado
Cuando  se está logueado
> form review

- src/Components/Login/Profile.jsx
- src/Components/Login/Singup.jsx
- src/Components/Nav/Nav.jsx
- src/Components/Register/Register.jsx
Bueno, controlamos en el componente de Register que el usuario ya registrado, no pueda volver a registrarse nuevamente.. lanzando un alert y redireccionándolo al Home. 
Por otro lado, queremos sacar el profile del nav mientras el user esta haciendo su registro, para así no salteárselo. 
Nota: También deberíamos deshabilitar el nav al momento de completar el registro del user. 
Archivos modificados: Profile, SingUp, Nav, Register.
> register alert y mas

- src/App.js
- src/Components/Home/Home.jsx
- src/Components/Nav/Nav.jsx
- src/Components/Register/Register.jsx
- src/Context/useExistUserDb.js
Se hizo verificaciones para que no carguen los componentes si esta autenticado pero no registrado, pero si le permite verlos como invitado y autenticado y registrado
Se implenta esta logica para verificar el email
Se hace este renderizado condicional donde si esta auth y registrado o no muestre todo
Y muestre esto si no esta registrado
Cuando cargue el home lo redirige al register
y estoy tratando de hacer el custom hook para llamarlo en los componentes necesarios
> Verificacion de registro del mail

- src/App.js
agregado de rutas en App de afiliacion socios
> agregado de rutas en App de afiliacion socios

- src/Actions/AppActions/appActions.js
- src/App.js
- src/Components/Home/Home.jsx
- src/Components/Nav/Nav.jsx
- src/Components/Register/Register.jsx
- src/Context/useExistUserDb.js
- src/Reducer/index.js
Se arregl los bucles infinitos que generaban las llamadas a getUser en varios componentes
> Reparar bucles infinitos del app.js nav.js

- src/Components/Home/Home.jsx
- src/Components/Register/Register.jsx
> Pruebas Register

- src/Components/CartSidebar/CartSidebar.css
- src/Components/CartSidebar/CartSidebar.jsx
- src/Components/Checkout/Checkout.jsx
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Payment/Payment.jsx
agregue un input para seleccion de cantidad de tickets
El carrito renderiza una sola card por item agregado y permite modificar cantidad en el carrito
El carrito suma el total de los productos 
Componente checkout trae la informacion correcta igual payment
> Logica del carrito al 100% mas arreglos Visuales

- src/Components/Paypal/PayPal.js
Ahora vacia el carrito al haber efectuado el pago y redirige a los eventos.
> Redireccion de Paypal y vaciado del carrito al pagar

- src/Actions/AppActions/appActions.js
- src/Components/Paypal/PayPal.js
- src/Reducer/index.js
Hice pruebas para generar el post de tickets y hice la action del mismo, con la alert de swal
Todo funcionando.
> pruebas de los ticket de paypal/action/Reducer

- src/Components/Paypal/PayPal.js
> paypal post Bry

- src/Components/EventDetails/EventDetail.css
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Membership/MembershipBasic.jsx
- src/Components/Membership/MembershipEco.jsx
- src/Components/Membership/MembershipPaleo.jsx
- src/Components/Nav/Nav.css
- src/Components/Nav/Nav.jsx
- src/Components/PricingTable/PricingTable.jsx
La asociacion entra al carrito
> arreglos carrito

- src/App.js
- src/Components/Galery/Galery.jsx
- src/Components/areaGeo/areaGeo.css
- src/Components/areaGeo/areaGeo.jsx
Se agrego pagina de Area Geologica y se vinculo con link correspondiente en home
> se agrego pagina Geo y ruta

- src/Components/Dashboard/DashUser/DashboardUser.jsx
> visual dashuser

- src/Actions/AppActions/appActions.js
- src/Components/Register/Register.jsx
> form register

- src/Components/Dashboard/Canva1.jsx
> dash ticket x categoria

- src/Actions/AppActions/appActions.js
- src/App.js
- src/Components/Login/Login.css
- src/Components/Login/Profile.jsx
- src/Components/Nav/Nav.css
- src/Components/Nav/Nav.jsx
- src/Reducer/index.js
> dash por role

- src/Components/Activities/Culture/Culture.jsx
- src/Components/Activities/Holidays/Holidays.jsx
- src/Components/Activities/Night/Night.jsx
- src/Components/CartSidebar/CartSidebar.css
- src/Components/CartSidebar/CartSidebar.jsx
- src/Components/Entradas/Entradas.css
- src/Components/Entradas/Entradas.jsx
- src/Components/Footer/Footer.jsx
- src/Components/Historia/Historia.css
- src/Components/Historia/Historia.jsx
- src/Components/Membership/MembershipBasic.jsx
- src/Components/Membership/MembershipEco.jsx
- src/Components/Membership/MembershipPaleo.jsx
- src/Components/PricingTable/PricingTable.jsx
- src/Components/areaBio/areaBio.jsx
en general:
se agrego boton history en Asociados, separacion de botones de margenes de sus respectivos div
Alerta elemento agregado al carrito
Arreglo de botones CartSideBar
Orden de botones en Entradas
Se reparo todos los estilos del componente historia, se agrego boton de asociado, se cambio el color del fondo
se acomodo el footer, se inserto logo del museo
y no me acuerdo que mas je
> se corrigieron estilos

- src/Components/Tickets/ListTicket.css
- src/Components/Tickets/ListTicket.jsx
> filtro por estado de ticket

- src/App.js
- src/Components/Comentarios/ComentariosyOpiniones.jsx
- src/Components/EventDetails/EventDetails.jsx
> borrado logico admin

- src/App.js
- src/Components/Dashboard/Canva4.jsx
- src/Components/Dashboard/Dashboard.jsx
- src/Components/EventDetails/EventDetail.css
- src/Components/Spin/Spin.css
- src/Components/Spin/Spin.jsx
> loading page

- src/Components/CartSidebar/CartSidebar.jsx
- src/Components/Checkout/Checkout.css
- src/Components/Checkout/Checkout.jsx
- src/Components/Entradas/Entradas.jsx
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Payment/Payment.jsx
Nueva propuesta en checkout con ANTD
Replicada en la parte de Payment
> cambios visuales, checkout y payment

- src/Actions/AppActions/appActions.js
- src/Components/Comentarios/ComentariosyOpiniones.jsx
- src/Components/Comentarios/FormReview.jsx
- src/Components/Dashboard/Perfil/PerfilAnt.jsx
- src/Components/Entradas/Entradas.jsx
- src/Components/EventDetails/EventDetail.css
- src/Components/EventDetails/EventDetails.jsx
- src/Components/Eventos/EventosList.jsx
- src/Components/FormCreacion/CrearCategoria.jsx
- src/Components/FormCreacion/CrearEvento.jsx
- src/Components/FormCreacion/CrearGuia.jsx
- src/Components/FormCreacion/CrearUsuario.jsx
- src/Components/FormCreacion/EliminarEvento.jsx
- src/Components/FormCreacion/EliminarGuia.jsx
- src/Components/FormCreacion/EliminarUsuario.jsx
- src/Components/FormCreacion/ModificarComentario.jsx
- src/Components/FormCreacion/ModificarEvento.jsx
- src/Components/FormCreacion/ModificarGuia.jsx
- src/Components/FormCreacion/ModificarUsuario.jsx
- src/Components/Membership/MembershipBasic.jsx
- src/Components/Membership/MembershipEco.jsx
- src/Components/Membership/MembershipPaleo.jsx
- src/Components/Paypal/PayPal.js
- src/Components/Register/Register.jsx
- src/Components/Tickets/ListTicket.jsx
> color swal alert

- src/Components/Dashboard/Perfil/PerfilAnt.jsx
- src/Components/Tickets/ListTicket.jsx
> fecha en tickets

- src/Components/Activities/Culture/Culture.jsx
- src/Components/Activities/Holidays/Holidays.jsx
- src/Components/Footer/Footer.jsx
- src/Components/Historia/Historia.css
- src/Components/Historia/Historia.jsx
- src/Components/InfoGeneral/InfoGeneral.jsx
- src/Components/InfoGeneral/PrecioEntrada.jsx
- src/Components/InfoGeneral/Styles/InfoGeneral.css
- src/Components/InfoGeneral/Styles/PrecioEntrada.css
- src/Components/Paginado/Paginado.jsx
- src/Components/areaBio/areaBio.jsx
- src/Components/areaEducation/areaEducation.jsx
Se tocaron varios componentes para adaptacion responsive
> responsive

- .env
- src/Components/Register/Register.jsx
> Reparacion de Mailer

- src/Actions/AppActions/appActions.js
- src/App.js
- src/Components/Membership/MembershipBasic.jsx
- src/Components/Membership/MembershipEco.jsx
- src/Components/Membership/MembershipPaleo.jsx
- src/Components/Paypal/PayPal.js
- src/Components/Paypal/PayPalSubscripcion.js
- src/Reducer/index.js
Por cuestiones de practicidad decidimos hacer que las subscripciones tengas su propio bottom de paypal
Te restringe la compra de la misma subscripcion y si compras otra te cambia el estado de la anterio y te setea la nueva
y manda el correo
> paypalSubscriber

- src/Components/Carrousel/Carrousel.css
- src/Components/Carrousel/EventsCarousel.jsx
- src/Components/Eventos/EventosList.jsx
Creacion de carrusel de eventos
> carrusel de eventos creado e incluido en event detail

- src/Components/Comentarios/FormReview.css
- src/Components/Comentarios/FormReview.jsx
- src/Components/EventDetails/EventDetail.css
- src/Components/EventDetails/EventDetails.jsx
Se centro y agrando input comentarios, estrellas y boton enviar. Se agrego boton volver
> arreglos en eventDetail

- src/Components/Comentarios/CommentForm.css
- src/Components/Comentarios/FormReview.css
- src/Components/EventDetails/EventDetail.css
> Responsivo de comentarios

- src/Components/Checkout/Checkout.jsx
- src/Components/Entradas/Entradas.css
- src/Components/Entradas/Entradas.jsx
Responsive entradas y checkout
> responsive entradas/checkout

- src/App.js
- src/Components/Sobre Nosotros/FormContact.jsx
> 'FormContacto Funcionando'

- src/Components/Exhibits/Exhibits.css
- src/Components/Exhibits/Exhibits.jsx
> "Detalles de Exhibiciones"
